// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.V1.Workspaces.Item.Git.Refresh;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.V1.Workspaces.Item.Git
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\{id}\git
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GitRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The refresh property</summary>
        public global::ApiSdk.V1.Workspaces.Item.Git.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::ApiSdk.V1.Workspaces.Item.Git.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Workspaces.Item.Git.GitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{id}/git", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Workspaces.Item.Git.GitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{id}/git", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
