// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CacheBudget : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The maxBytes property</summary>
        public long? MaxBytes { get; set; }
        /// <summary>The maxFiles property</summary>
        public int? MaxFiles { get; set; }
        /// <summary>The maxFileSize property</summary>
        public long? MaxFileSize { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.CacheBudget"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.CacheBudget CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.CacheBudget();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "maxBytes", n => { MaxBytes = n.GetLongValue(); } },
                { "maxFileSize", n => { MaxFileSize = n.GetLongValue(); } },
                { "maxFiles", n => { MaxFiles = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("maxBytes", MaxBytes);
            writer.WriteIntValue("maxFiles", MaxFiles);
            writer.WriteLongValue("maxFileSize", MaxFileSize);
        }
    }
}
#pragma warning restore CS0618
