// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Case handling. 0.11 replaced the old `smart_case` boolean with this; the boolean remainsonly as a legacy fallback and is not offered here.Unlike `matchType`, this is a real enum in the engine, so closing it in the contract issafe and gives the C# client a proper enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CasingDto
    {
        [EnumMember(Value = "smart")]
        #pragma warning disable CS1591
        Smart,
        #pragma warning restore CS1591
        [EnumMember(Value = "sensitive")]
        #pragma warning disable CS1591
        Sensitive,
        #pragma warning restore CS1591
        [EnumMember(Value = "insensitive")]
        #pragma warning disable CS1591
        Insensitive,
        #pragma warning restore CS1591
    }
}
