// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>What kind of thing a constraint constrains.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConstraintType
    {
        [EnumMember(Value = "extension")]
        #pragma warning disable CS1591
        Extension,
        #pragma warning restore CS1591
        [EnumMember(Value = "glob")]
        #pragma warning disable CS1591
        Glob,
        #pragma warning restore CS1591
        [EnumMember(Value = "parts")]
        #pragma warning disable CS1591
        Parts,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "exclude")]
        #pragma warning disable CS1591
        Exclude,
        #pragma warning restore CS1591
        [EnumMember(Value = "pathSegment")]
        #pragma warning disable CS1591
        PathSegment,
        #pragma warning restore CS1591
        [EnumMember(Value = "filePath")]
        #pragma warning disable CS1591
        FilePath,
        #pragma warning restore CS1591
        [EnumMember(Value = "fileType")]
        #pragma warning disable CS1591
        FileType,
        #pragma warning restore CS1591
        [EnumMember(Value = "gitStatus")]
        #pragma warning disable CS1591
        GitStatus,
        #pragma warning restore CS1591
    }
}
