// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Per-workspace options, all defaulting from `[defaults]` in the config file.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateWorkspace : IParsable
    {
        /// <summary>`FFFMode::Ai` when true. Changes frecency decay, modification-score thresholds andwatcher event handling. Fixed for the workspace&apos;s life.</summary>
        public bool? AiMode { get; set; }
        /// <summary>The cacheBudget property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.CacheBudget? CacheBudget { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.CacheBudget CacheBudget { get; set; }
#endif
        /// <summary>Builds the bigram content index (~360 bytes/file). Required for typo-resistant andfuzzy grep. Measured at roughly 20x the cost of the directory walk.</summary>
        public bool? ContentIndexing { get; set; }
        /// <summary>The followSymlinks property</summary>
        public bool? FollowSymlinks { get; set; }
        /// <summary>The gitRecency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.GitRecency? GitRecency { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.GitRecency GitRecency { get; set; }
#endif
        /// <summary>Path to index. Any spelling; it is canonicalised and deduplicated by filesystemidentity, so a UNC path and a mapped drive pointing at one directory give oneworkspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Root { get; set; }
#nullable restore
#else
        public string Root { get; set; }
#endif
        /// <summary>Which readiness stage to block for.</summary>
        public global::ApiSdk.Models.WaitFor? WaitFor { get; set; }
        /// <summary>Overrides `workspaces.create_block_ms` for this call.</summary>
        public long? WaitForIndexMs { get; set; }
        /// <summary>Background filesystem watcher. Verified working over SMB (~500ms).</summary>
        public bool? Watch { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.CreateWorkspace"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.CreateWorkspace CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.CreateWorkspace();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aiMode", n => { AiMode = n.GetBoolValue(); } },
                { "cacheBudget", n => { CacheBudget = n.GetObjectValue<global::ApiSdk.Models.CacheBudget>(global::ApiSdk.Models.CacheBudget.CreateFromDiscriminatorValue); } },
                { "contentIndexing", n => { ContentIndexing = n.GetBoolValue(); } },
                { "followSymlinks", n => { FollowSymlinks = n.GetBoolValue(); } },
                { "gitRecency", n => { GitRecency = n.GetObjectValue<global::ApiSdk.Models.GitRecency>(global::ApiSdk.Models.GitRecency.CreateFromDiscriminatorValue); } },
                { "root", n => { Root = n.GetStringValue(); } },
                { "waitFor", n => { WaitFor = n.GetEnumValue<global::ApiSdk.Models.WaitFor>(); } },
                { "waitForIndexMs", n => { WaitForIndexMs = n.GetLongValue(); } },
                { "watch", n => { Watch = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aiMode", AiMode);
            writer.WriteObjectValue<global::ApiSdk.Models.CacheBudget>("cacheBudget", CacheBudget);
            writer.WriteBoolValue("contentIndexing", ContentIndexing);
            writer.WriteBoolValue("followSymlinks", FollowSymlinks);
            writer.WriteObjectValue<global::ApiSdk.Models.GitRecency>("gitRecency", GitRecency);
            writer.WriteStringValue("root", Root);
            writer.WriteEnumValue<global::ApiSdk.Models.WaitFor>("waitFor", WaitFor);
            writer.WriteLongValue("waitForIndexMs", WaitForIndexMs);
            writer.WriteBoolValue("watch", Watch);
        }
    }
}
#pragma warning restore CS0618
