// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// The settings a workspace was actually created with, echoed back so a client never has toguess which defaults applied.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EffectiveOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aiMode property</summary>
        public bool? AiMode { get; set; }
        /// <summary>The contentIndexing property</summary>
        public bool? ContentIndexing { get; set; }
        /// <summary>The followSymlinks property</summary>
        public bool? FollowSymlinks { get; set; }
        /// <summary>The gitRecencyEnabled property</summary>
        public bool? GitRecencyEnabled { get; set; }
        /// <summary>The gitRecencyMaxCommits property</summary>
        public int? GitRecencyMaxCommits { get; set; }
        /// <summary>The gitRecencyMaxFilesPerCommit property</summary>
        public int? GitRecencyMaxFilesPerCommit { get; set; }
        /// <summary>The watch property</summary>
        public bool? Watch { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.EffectiveOptions"/> and sets the default values.
        /// </summary>
        public EffectiveOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.EffectiveOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.EffectiveOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.EffectiveOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aiMode", n => { AiMode = n.GetBoolValue(); } },
                { "contentIndexing", n => { ContentIndexing = n.GetBoolValue(); } },
                { "followSymlinks", n => { FollowSymlinks = n.GetBoolValue(); } },
                { "gitRecencyEnabled", n => { GitRecencyEnabled = n.GetBoolValue(); } },
                { "gitRecencyMaxCommits", n => { GitRecencyMaxCommits = n.GetIntValue(); } },
                { "gitRecencyMaxFilesPerCommit", n => { GitRecencyMaxFilesPerCommit = n.GetIntValue(); } },
                { "watch", n => { Watch = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aiMode", AiMode);
            writer.WriteBoolValue("contentIndexing", ContentIndexing);
            writer.WriteBoolValue("followSymlinks", FollowSymlinks);
            writer.WriteBoolValue("gitRecencyEnabled", GitRecencyEnabled);
            writer.WriteIntValue("gitRecencyMaxCommits", GitRecencyMaxCommits);
            writer.WriteIntValue("gitRecencyMaxFilesPerCommit", GitRecencyMaxFilesPerCommit);
            writer.WriteBoolValue("watch", Watch);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
