// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// An indexed file.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FileItemDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Native separators, and free of any `\\?\` prefix — so it is safe to open and safe todisplay. Not an identity key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AbsolutePath { get; set; }
#nullable restore
#else
        public string AbsolutePath { get; set; }
#endif
        /// <summary>The accessFrecencyScore property</summary>
        public int? AccessFrecencyScore { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Parent directory, with a trailing `/`. Empty at the root.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Directory { get; set; }
#nullable restore
#else
        public string Directory { get; set; }
#endif
        /// <summary>The fileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>Boost from recent commits on the current branch. Reported separately because`totalFrecencyScore` does **not** include it, so it would otherwise be invisible.</summary>
        public int? GitRecencyScore { get; set; }
        /// <summary>Git status, in full.`git2::Status` is a bitflags value — a file can be staged-modified *and* worktree-modifiedat once. Every other fff binding flattens it to one string and loses that, so both formsare emitted: `status` for convenience, `flags` for fidelity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.GitStatus? GitStatus { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.GitStatus GitStatus { get; set; }
#endif
        /// <summary>The isBinary property</summary>
        public bool? IsBinary { get; set; }
        /// <summary>The modificationFrecencyScore property</summary>
        public int? ModificationFrecencyScore { get; set; }
        /// <summary>The modified property</summary>
        public DateTimeOffset? Modified { get; set; }
        /// <summary>Repo-relative, **forward slashes on every platform**, carrying on-disk casing. Thisis what the engine stores and what globs and path constraints match against.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelativePath { get; set; }
#nullable restore
#else
        public string RelativePath { get; set; }
#endif
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>Access plus modification only — deliberately excluding `gitRecencyScore`, matchingthe engine&apos;s own `total_frecency_score()`.</summary>
        public int? TotalFrecencyScore { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.FileItemDto"/> and sets the default values.
        /// </summary>
        public FileItemDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.FileItemDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.FileItemDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.FileItemDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absolutePath", n => { AbsolutePath = n.GetStringValue(); } },
                { "accessFrecencyScore", n => { AccessFrecencyScore = n.GetIntValue(); } },
                { "directory", n => { Directory = n.GetStringValue(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "gitRecencyScore", n => { GitRecencyScore = n.GetIntValue(); } },
                { "gitStatus", n => { GitStatus = n.GetObjectValue<global::ApiSdk.Models.GitStatus>(global::ApiSdk.Models.GitStatus.CreateFromDiscriminatorValue); } },
                { "isBinary", n => { IsBinary = n.GetBoolValue(); } },
                { "modificationFrecencyScore", n => { ModificationFrecencyScore = n.GetIntValue(); } },
                { "modified", n => { Modified = n.GetDateTimeOffsetValue(); } },
                { "relativePath", n => { RelativePath = n.GetStringValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "totalFrecencyScore", n => { TotalFrecencyScore = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("absolutePath", AbsolutePath);
            writer.WriteIntValue("accessFrecencyScore", AccessFrecencyScore);
            writer.WriteStringValue("directory", Directory);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteIntValue("gitRecencyScore", GitRecencyScore);
            writer.WriteObjectValue<global::ApiSdk.Models.GitStatus>("gitStatus", GitStatus);
            writer.WriteBoolValue("isBinary", IsBinary);
            writer.WriteIntValue("modificationFrecencyScore", ModificationFrecencyScore);
            writer.WriteDateTimeOffsetValue("modified", Modified);
            writer.WriteStringValue("relativePath", RelativePath);
            writer.WriteLongValue("size", Size);
            writer.WriteIntValue("totalFrecencyScore", TotalFrecencyScore);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
