// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Git status filter, mirroring the engine&apos;s four categories.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GitStatusConstraint
    {
        [EnumMember(Value = "modified")]
        #pragma warning disable CS1591
        Modified,
        #pragma warning restore CS1591
        [EnumMember(Value = "untracked")]
        #pragma warning disable CS1591
        Untracked,
        #pragma warning restore CS1591
        [EnumMember(Value = "staged")]
        #pragma warning disable CS1591
        Staged,
        #pragma warning restore CS1591
        [EnumMember(Value = "unmodified")]
        #pragma warning disable CS1591
        Unmodified,
        #pragma warning restore CS1591
    }
}
