// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>How to interpret the pattern.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GrepModeDto
    {
        [EnumMember(Value = "plain")]
        #pragma warning disable CS1591
        Plain,
        #pragma warning restore CS1591
        [EnumMember(Value = "regex")]
        #pragma warning disable CS1591
        Regex,
        #pragma warning restore CS1591
        [EnumMember(Value = "fuzzy")]
        #pragma warning disable CS1591
        Fuzzy,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
    }
}
