// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Content search request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GrepRequest : IParsable
    {
        /// <summary>The afterContext property</summary>
        public int? AfterContext { get; set; }
        /// <summary>The beforeContext property</summary>
        public int? BeforeContext { get; set; }
        /// <summary>Case handling. 0.11 replaced the old `smart_case` boolean with this; the boolean remainsonly as a legacy fallback and is not offered here.Unlike `matchType`, this is a real enum in the engine, so closing it in the contract issafe and gives the C# client a proper enum.</summary>
        public global::ApiSdk.Models.CasingDto? Casing { get; set; }
        /// <summary>Tags lines that look like definitions. Roughly 2% overhead.</summary>
        public bool? ClassifyDefinitions { get; set; }
        /// <summary>Continuation token from a previous response&apos;s `nextCursor`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>Apply the budget even before anything has matched. Off by default, matching theengine: a zero-match query otherwise scans everything.</summary>
        public bool? EnforceTimeBudget { get; set; }
        /// <summary>The maxFileSize property</summary>
        public long? MaxFileSize { get; set; }
        /// <summary>The maxMatchesPerFile property</summary>
        public int? MaxMatchesPerFile { get; set; }
        /// <summary>How to interpret the pattern.</summary>
        public global::ApiSdk.Models.GrepModeDto? Mode { get; set; }
        /// <summary>Soft cap on matches per response; the engine finishes the file it is in.</summary>
        public int? PageSize { get; set; }
        /// <summary>Which parser preset to read constraint tokens with.</summary>
        public global::ApiSdk.Models.GrepPreset? Preset { get; set; }
        /// <summary>Pattern plus optional constraint tokens, e.g. `*.rs !tests/ TODO`. Passed to theengine byte-for-byte: backslashes are **not** folded, because a backslash islegitimate content in a pattern.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Milliseconds before returning partial results. 0, the default, means unbounded.Grep over SMB measured ~7 ms/file, so a full 87k-file tree is around ten minutes: abudget here is a real safeguard, but one that silently truncates, which is whycursor paging is the better tool.</summary>
        public long? TimeBudgetMs { get; set; }
        /// <summary>Strips leading whitespace from matched and context lines, adjusting the reportedoffsets accordingly.</summary>
        public bool? TrimWhitespace { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.GrepRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.GrepRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.GrepRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "afterContext", n => { AfterContext = n.GetIntValue(); } },
                { "beforeContext", n => { BeforeContext = n.GetIntValue(); } },
                { "casing", n => { Casing = n.GetEnumValue<global::ApiSdk.Models.CasingDto>(); } },
                { "classifyDefinitions", n => { ClassifyDefinitions = n.GetBoolValue(); } },
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "enforceTimeBudget", n => { EnforceTimeBudget = n.GetBoolValue(); } },
                { "maxFileSize", n => { MaxFileSize = n.GetLongValue(); } },
                { "maxMatchesPerFile", n => { MaxMatchesPerFile = n.GetIntValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::ApiSdk.Models.GrepModeDto>(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "preset", n => { Preset = n.GetEnumValue<global::ApiSdk.Models.GrepPreset>(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "timeBudgetMs", n => { TimeBudgetMs = n.GetLongValue(); } },
                { "trimWhitespace", n => { TrimWhitespace = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("afterContext", AfterContext);
            writer.WriteIntValue("beforeContext", BeforeContext);
            writer.WriteEnumValue<global::ApiSdk.Models.CasingDto>("casing", Casing);
            writer.WriteBoolValue("classifyDefinitions", ClassifyDefinitions);
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteBoolValue("enforceTimeBudget", EnforceTimeBudget);
            writer.WriteLongValue("maxFileSize", MaxFileSize);
            writer.WriteIntValue("maxMatchesPerFile", MaxMatchesPerFile);
            writer.WriteEnumValue<global::ApiSdk.Models.GrepModeDto>("mode", Mode);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteEnumValue<global::ApiSdk.Models.GrepPreset>("preset", Preset);
            writer.WriteStringValue("query", Query);
            writer.WriteLongValue("timeBudgetMs", TimeBudgetMs);
            writer.WriteBoolValue("trimWhitespace", TrimWhitespace);
        }
    }
}
#pragma warning restore CS0618
