// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// One matching line.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GrepMatchDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Byte offset of this line within the file. Stays a byte count, because that is what itis for: seeking directly to the line.</summary>
        public long? ByteOffset { get; set; }
        /// <summary>Column of the first match on this line, in **UTF-16 code units** into `lineContent`.</summary>
        public int? ColUtf16 { get; set; }
        /// <summary>The contextAfter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ContextAfter { get; set; }
#nullable restore
#else
        public List<string> ContextAfter { get; set; }
#endif
        /// <summary>The contextBefore property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ContextBefore { get; set; }
#nullable restore
#else
        public List<string> ContextBefore { get; set; }
#endif
        /// <summary>Index into the response&apos;s `files` array. Kept as an index rather than embedding thefile, so a file&apos;s metadata is not repeated across hundreds of matches within it.</summary>
        public int? FileIndex { get; set; }
        /// <summary>Only present in fuzzy mode.</summary>
        public int? FuzzyScore { get; set; }
        /// <summary>Only meaningful when `classifyDefinitions` was requested.</summary>
        public bool? IsDefinition { get; set; }
        /// <summary>The lineContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LineContent { get; set; }
#nullable restore
#else
        public string LineContent { get; set; }
#endif
        /// <summary>1-based.</summary>
        public long? LineNumber { get; set; }
        /// <summary>Every match on this line, in UTF-16 code units into `lineContent`. The MCP serveruses these only to centre its truncation window and never emits them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.Utf16Range>? MatchRangesUtf16 { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.Utf16Range> MatchRangesUtf16 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.GrepMatchDto"/> and sets the default values.
        /// </summary>
        public GrepMatchDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.GrepMatchDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.GrepMatchDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.GrepMatchDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "byteOffset", n => { ByteOffset = n.GetLongValue(); } },
                { "colUtf16", n => { ColUtf16 = n.GetIntValue(); } },
                { "contextAfter", n => { ContextAfter = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contextBefore", n => { ContextBefore = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "fileIndex", n => { FileIndex = n.GetIntValue(); } },
                { "fuzzyScore", n => { FuzzyScore = n.GetIntValue(); } },
                { "isDefinition", n => { IsDefinition = n.GetBoolValue(); } },
                { "lineContent", n => { LineContent = n.GetStringValue(); } },
                { "lineNumber", n => { LineNumber = n.GetLongValue(); } },
                { "matchRangesUtf16", n => { MatchRangesUtf16 = n.GetCollectionOfObjectValues<global::ApiSdk.Models.Utf16Range>(global::ApiSdk.Models.Utf16Range.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("byteOffset", ByteOffset);
            writer.WriteIntValue("colUtf16", ColUtf16);
            writer.WriteCollectionOfPrimitiveValues<string>("contextAfter", ContextAfter);
            writer.WriteCollectionOfPrimitiveValues<string>("contextBefore", ContextBefore);
            writer.WriteIntValue("fileIndex", FileIndex);
            writer.WriteIntValue("fuzzyScore", FuzzyScore);
            writer.WriteBoolValue("isDefinition", IsDefinition);
            writer.WriteStringValue("lineContent", LineContent);
            writer.WriteLongValue("lineNumber", LineNumber);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.Utf16Range>("matchRangesUtf16", MatchRangesUtf16);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
