// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Which parser preset to read constraint tokens with.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GrepPreset
    {
        [EnumMember(Value = "grep")]
        #pragma warning disable CS1591
        Grep,
        #pragma warning restore CS1591
        [EnumMember(Value = "aiGrep")]
        #pragma warning disable CS1591
        AiGrep,
        #pragma warning restore CS1591
    }
}
