// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GrepResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>True when the engine&apos;s abort signal was tripped, which currently means the clientdisconnected mid-search. Results are partial.Note this does **not** cover a `timeBudgetMs` truncation: the engine reports that byreturning early with a non-null `nextCursor` and no separate flag, so a client thatcares about completeness should page until `nextCursor` is null rather than trustthis field alone.</summary>
        public bool? Aborted { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deduplicated files referenced by `matches[].fileIndex`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.FileItemDto>? Files { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.FileItemDto> Files { get; set; }
#endif
        /// <summary>The filesWithMatches property</summary>
        public int? FilesWithMatches { get; set; }
        /// <summary>Files eligible after filtering out binaries, oversized files and constraint misses.</summary>
        public int? FilteredFileCount { get; set; }
        /// <summary>True when a constrained query found nothing and the engine retried the whole rawquery as literal text, ignoring the constraints it had inferred.</summary>
        public bool? LiteralFallback { get; set; }
        /// <summary>The matches property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.GrepMatchDto>? Matches { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.GrepMatchDto> Matches { get; set; }
#endif
        /// <summary>The mode actually used, after `auto` resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mode { get; set; }
#nullable restore
#else
        public string Mode { get; set; }
#endif
        /// <summary>Pass back as `cursor` for the next page. `null` means the search is exhausted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>Set when a regex failed to compile and the search fell back to literal matching.The request still succeeds; this explains why the results look literal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegexFallbackError { get; set; }
#nullable restore
#else
        public string RegexFallbackError { get; set; }
#endif
        /// <summary>Files in the index.</summary>
        public int? TotalFiles { get; set; }
        /// <summary>Files actually searched in this call.</summary>
        public int? TotalFilesSearched { get; set; }
        /// <summary>The totalMatched property</summary>
        public int? TotalMatched { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.GrepResponse"/> and sets the default values.
        /// </summary>
        public GrepResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.GrepResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.GrepResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.GrepResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aborted", n => { Aborted = n.GetBoolValue(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::ApiSdk.Models.FileItemDto>(global::ApiSdk.Models.FileItemDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "filesWithMatches", n => { FilesWithMatches = n.GetIntValue(); } },
                { "filteredFileCount", n => { FilteredFileCount = n.GetIntValue(); } },
                { "literalFallback", n => { LiteralFallback = n.GetBoolValue(); } },
                { "matches", n => { Matches = n.GetCollectionOfObjectValues<global::ApiSdk.Models.GrepMatchDto>(global::ApiSdk.Models.GrepMatchDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mode", n => { Mode = n.GetStringValue(); } },
                { "nextCursor", n => { NextCursor = n.GetStringValue(); } },
                { "regexFallbackError", n => { RegexFallbackError = n.GetStringValue(); } },
                { "totalFiles", n => { TotalFiles = n.GetIntValue(); } },
                { "totalFilesSearched", n => { TotalFilesSearched = n.GetIntValue(); } },
                { "totalMatched", n => { TotalMatched = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aborted", Aborted);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.FileItemDto>("files", Files);
            writer.WriteIntValue("filesWithMatches", FilesWithMatches);
            writer.WriteIntValue("filteredFileCount", FilteredFileCount);
            writer.WriteBoolValue("literalFallback", LiteralFallback);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.GrepMatchDto>("matches", Matches);
            writer.WriteStringValue("mode", Mode);
            writer.WriteStringValue("nextCursor", NextCursor);
            writer.WriteStringValue("regexFallbackError", RegexFallbackError);
            writer.WriteIntValue("totalFiles", TotalFiles);
            writer.WriteIntValue("totalFilesSearched", TotalFilesSearched);
            writer.WriteIntValue("totalMatched", TotalMatched);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
