// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Which parts of a location the query specified.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LocationType
    {
        [EnumMember(Value = "line")]
        #pragma warning disable CS1591
        Line,
        #pragma warning restore CS1591
        [EnumMember(Value = "position")]
        #pragma warning disable CS1591
        Position,
        #pragma warning restore CS1591
        [EnumMember(Value = "range")]
        #pragma warning disable CS1591
        Range,
        #pragma warning restore CS1591
    }
}
