// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// A `file.ts:42:10` suffix parsed out of the query. `line` is always present; `col`,`endLine` and `endCol` depend on `type`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocationDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Present for `position` and `range`.</summary>
        public int? Col { get; set; }
        /// <summary>Present for `range` only.</summary>
        public int? EndCol { get; set; }
        /// <summary>Present for `range` only.</summary>
        public int? EndLine { get; set; }
        /// <summary>The line property</summary>
        public int? Line { get; set; }
        /// <summary>Which parts of a location the query specified.</summary>
        public global::ApiSdk.Models.LocationType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.LocationDto"/> and sets the default values.
        /// </summary>
        public LocationDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.LocationDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.LocationDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.LocationDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "col", n => { Col = n.GetIntValue(); } },
                { "endCol", n => { EndCol = n.GetIntValue(); } },
                { "endLine", n => { EndLine = n.GetIntValue(); } },
                { "line", n => { Line = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::ApiSdk.Models.LocationType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("col", Col);
            writer.WriteIntValue("endCol", EndCol);
            writer.WriteIntValue("endLine", EndLine);
            writer.WriteIntValue("line", Line);
            writer.WriteEnumValue<global::ApiSdk.Models.LocationType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
