// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// A hit from a mixed search. Exactly one of `file` and `directory` is populated, indicatedby `type`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MixedHit : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The directory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DirItemDto? Directory { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DirItemDto Directory { get; set; }
#endif
        /// <summary>The file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.FileItemDto? File { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.FileItemDto File { get; set; }
#endif
        /// <summary>The complete score breakdown: all 13 fields the engine computes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.ScoreDto? Score { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.ScoreDto Score { get; set; }
#endif
        /// <summary>Whether a mixed hit is a file or a directory.</summary>
        public global::ApiSdk.Models.MixedKind? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.MixedHit"/> and sets the default values.
        /// </summary>
        public MixedHit()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.MixedHit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.MixedHit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.MixedHit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "directory", n => { Directory = n.GetObjectValue<global::ApiSdk.Models.DirItemDto>(global::ApiSdk.Models.DirItemDto.CreateFromDiscriminatorValue); } },
                { "file", n => { File = n.GetObjectValue<global::ApiSdk.Models.FileItemDto>(global::ApiSdk.Models.FileItemDto.CreateFromDiscriminatorValue); } },
                { "score", n => { Score = n.GetObjectValue<global::ApiSdk.Models.ScoreDto>(global::ApiSdk.Models.ScoreDto.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::ApiSdk.Models.MixedKind>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ApiSdk.Models.DirItemDto>("directory", Directory);
            writer.WriteObjectValue<global::ApiSdk.Models.FileItemDto>("file", File);
            writer.WriteObjectValue<global::ApiSdk.Models.ScoreDto>("score", Score);
            writer.WriteEnumValue<global::ApiSdk.Models.MixedKind>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
