// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Whether a mixed hit is a file or a directory.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MixedKind
    {
        [EnumMember(Value = "file")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
        [EnumMember(Value = "directory")]
        #pragma warning disable CS1591
        Directory,
        #pragma warning restore CS1591
    }
}
