// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MixedSearchResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The hasMore property</summary>
        public bool? HasMore { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.MixedHit>? Items { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.MixedHit> Items { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.LocationDto? Location { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.LocationDto Location { get; set; }
#endif
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>The totalDirs property</summary>
        public int? TotalDirs { get; set; }
        /// <summary>The totalFiles property</summary>
        public int? TotalFiles { get; set; }
        /// <summary>The totalMatched property</summary>
        public int? TotalMatched { get; set; }
        /// <summary>The warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Warnings { get; set; }
#nullable restore
#else
        public List<string> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.MixedSearchResponse"/> and sets the default values.
        /// </summary>
        public MixedSearchResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.MixedSearchResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.MixedSearchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.MixedSearchResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hasMore", n => { HasMore = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::ApiSdk.Models.MixedHit>(global::ApiSdk.Models.MixedHit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "location", n => { Location = n.GetObjectValue<global::ApiSdk.Models.LocationDto>(global::ApiSdk.Models.LocationDto.CreateFromDiscriminatorValue); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "totalDirs", n => { TotalDirs = n.GetIntValue(); } },
                { "totalFiles", n => { TotalFiles = n.GetIntValue(); } },
                { "totalMatched", n => { TotalMatched = n.GetIntValue(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("hasMore", HasMore);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.MixedHit>("items", Items);
            writer.WriteObjectValue<global::ApiSdk.Models.LocationDto>("location", Location);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteIntValue("totalDirs", TotalDirs);
            writer.WriteIntValue("totalFiles", TotalFiles);
            writer.WriteIntValue("totalMatched", TotalMatched);
            writer.WriteCollectionOfPrimitiveValues<string>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
