// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Multi-pattern search: any pattern matching counts, via SIMD Aho-Corasick. Faster thanregex alternation and much faster than N separate searches. Always literal text.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MultiGrepRequest : IParsable
    {
        /// <summary>The afterContext property</summary>
        public int? AfterContext { get; set; }
        /// <summary>The beforeContext property</summary>
        public int? BeforeContext { get; set; }
        /// <summary>Case handling. 0.11 replaced the old `smart_case` boolean with this; the boolean remainsonly as a legacy fallback and is not offered here.Unlike `matchType`, this is a real enum in the engine, so closing it in the contract issafe and gives the C# client a proper enum.</summary>
        public global::ApiSdk.Models.CasingDto? Casing { get; set; }
        /// <summary>The classifyDefinitions property</summary>
        public bool? ClassifyDefinitions { get; set; }
        /// <summary>Constraint tokens only — no pattern text. e.g. `*.rs !tests/`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Constraints { get; set; }
#nullable restore
#else
        public string Constraints { get; set; }
#endif
        /// <summary>The cursor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>The enforceTimeBudget property</summary>
        public bool? EnforceTimeBudget { get; set; }
        /// <summary>The maxFileSize property</summary>
        public long? MaxFileSize { get; set; }
        /// <summary>The maxMatchesPerFile property</summary>
        public int? MaxMatchesPerFile { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>At least one literal pattern.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Patterns { get; set; }
#nullable restore
#else
        public List<string> Patterns { get; set; }
#endif
        /// <summary>Which parser preset to read constraint tokens with.</summary>
        public global::ApiSdk.Models.GrepPreset? Preset { get; set; }
        /// <summary>The timeBudgetMs property</summary>
        public long? TimeBudgetMs { get; set; }
        /// <summary>The trimWhitespace property</summary>
        public bool? TrimWhitespace { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.MultiGrepRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.MultiGrepRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.MultiGrepRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "afterContext", n => { AfterContext = n.GetIntValue(); } },
                { "beforeContext", n => { BeforeContext = n.GetIntValue(); } },
                { "casing", n => { Casing = n.GetEnumValue<global::ApiSdk.Models.CasingDto>(); } },
                { "classifyDefinitions", n => { ClassifyDefinitions = n.GetBoolValue(); } },
                { "constraints", n => { Constraints = n.GetStringValue(); } },
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "enforceTimeBudget", n => { EnforceTimeBudget = n.GetBoolValue(); } },
                { "maxFileSize", n => { MaxFileSize = n.GetLongValue(); } },
                { "maxMatchesPerFile", n => { MaxMatchesPerFile = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "patterns", n => { Patterns = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "preset", n => { Preset = n.GetEnumValue<global::ApiSdk.Models.GrepPreset>(); } },
                { "timeBudgetMs", n => { TimeBudgetMs = n.GetLongValue(); } },
                { "trimWhitespace", n => { TrimWhitespace = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("afterContext", AfterContext);
            writer.WriteIntValue("beforeContext", BeforeContext);
            writer.WriteEnumValue<global::ApiSdk.Models.CasingDto>("casing", Casing);
            writer.WriteBoolValue("classifyDefinitions", ClassifyDefinitions);
            writer.WriteStringValue("constraints", Constraints);
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteBoolValue("enforceTimeBudget", EnforceTimeBudget);
            writer.WriteLongValue("maxFileSize", MaxFileSize);
            writer.WriteIntValue("maxMatchesPerFile", MaxMatchesPerFile);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteCollectionOfPrimitiveValues<string>("patterns", Patterns);
            writer.WriteEnumValue<global::ApiSdk.Models.GrepPreset>("preset", Preset);
            writer.WriteLongValue("timeBudgetMs", TimeBudgetMs);
            writer.WriteBoolValue("trimWhitespace", TrimWhitespace);
        }
    }
}
#pragma warning restore CS0618
