// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// How the parser decomposed a query.Exists because the DSL is powerful and silent about mistakes: a token that looks like aglob but is not recognised as one simply becomes fuzzy text, and the results still lookplausible. This endpoint makes that visible from the client side.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParseQueryResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The constraints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.ConstraintDto>? Constraints { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.ConstraintDto> Constraints { get; set; }
#endif
        /// <summary>The fuzzy terms left after constraints were removed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FuzzyParts { get; set; }
#nullable restore
#else
        public List<string> FuzzyParts { get; set; }
#endif
        /// <summary>What grep would search for: the query minus constraint tokens.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GrepText { get; set; }
#nullable restore
#else
        public string GrepText { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.LocationDto? Location { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.LocationDto Location { get; set; }
#endif
        /// <summary>Echoed back, byte-for-byte.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Problems that would otherwise pass unnoticed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Warnings { get; set; }
#nullable restore
#else
        public List<string> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.ParseQueryResponse"/> and sets the default values.
        /// </summary>
        public ParseQueryResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.ParseQueryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.ParseQueryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.ParseQueryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "constraints", n => { Constraints = n.GetCollectionOfObjectValues<global::ApiSdk.Models.ConstraintDto>(global::ApiSdk.Models.ConstraintDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fuzzyParts", n => { FuzzyParts = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "grepText", n => { GrepText = n.GetStringValue(); } },
                { "location", n => { Location = n.GetObjectValue<global::ApiSdk.Models.LocationDto>(global::ApiSdk.Models.LocationDto.CreateFromDiscriminatorValue); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.ConstraintDto>("constraints", Constraints);
            writer.WriteCollectionOfPrimitiveValues<string>("fuzzyParts", FuzzyParts);
            writer.WriteStringValue("grepText", GrepText);
            writer.WriteObjectValue<global::ApiSdk.Models.LocationDto>("location", Location);
            writer.WriteStringValue("query", Query);
            writer.WriteCollectionOfPrimitiveValues<string>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
