// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Which preset to parse with. The presets differ in which constraint kinds they recognise,so the same string can mean different things.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParsePreset
    {
        [EnumMember(Value = "fileSearch")]
        #pragma warning disable CS1591
        FileSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "dirSearch")]
        #pragma warning disable CS1591
        DirSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "mixedSearch")]
        #pragma warning disable CS1591
        MixedSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "grep")]
        #pragma warning disable CS1591
        Grep,
        #pragma warning restore CS1591
        [EnumMember(Value = "aiGrep")]
        #pragma warning disable CS1591
        AiGrep,
        #pragma warning restore CS1591
    }
}
