// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// The complete score breakdown: all 13 fields the engine computes.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScoreDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The baseScore property</summary>
        public int? BaseScore { get; set; }
        /// <summary>The comboMatchBoost property</summary>
        public int? ComboMatchBoost { get; set; }
        /// <summary>The currentFilePenalty property</summary>
        public int? CurrentFilePenalty { get; set; }
        /// <summary>The distancePenalty property</summary>
        public int? DistancePenalty { get; set; }
        /// <summary>The exactMatch property</summary>
        public bool? ExactMatch { get; set; }
        /// <summary>The filenameBonus property</summary>
        public int? FilenameBonus { get; set; }
        /// <summary>The frecencyBoost property</summary>
        public int? FrecencyBoost { get; set; }
        /// <summary>Added in fff 0.11; absent from every other binding.</summary>
        public int? GitRecencyBoost { get; set; }
        /// <summary>Dropped by the C ABI and by the TypeScript SDK.</summary>
        public int? GitStatusBoost { get; set; }
        /// <summary>Documented as an **open** string, not a closed enum: it is a bare `&amp;&apos;static str` inthe engine with no enum backing it, so a future value must not break a client.Known values include `fuzzy`, `fuzzy_filename`, `exact`, `prefix`, `path`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MatchType { get; set; }
#nullable restore
#else
        public string MatchType { get; set; }
#endif
        /// <summary>Dropped by the TypeScript SDK.</summary>
        public int? PathAlignmentBonus { get; set; }
        /// <summary>The specialFilenameBonus property</summary>
        public int? SpecialFilenameBonus { get; set; }
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.ScoreDto"/> and sets the default values.
        /// </summary>
        public ScoreDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.ScoreDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.ScoreDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.ScoreDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseScore", n => { BaseScore = n.GetIntValue(); } },
                { "comboMatchBoost", n => { ComboMatchBoost = n.GetIntValue(); } },
                { "currentFilePenalty", n => { CurrentFilePenalty = n.GetIntValue(); } },
                { "distancePenalty", n => { DistancePenalty = n.GetIntValue(); } },
                { "exactMatch", n => { ExactMatch = n.GetBoolValue(); } },
                { "filenameBonus", n => { FilenameBonus = n.GetIntValue(); } },
                { "frecencyBoost", n => { FrecencyBoost = n.GetIntValue(); } },
                { "gitRecencyBoost", n => { GitRecencyBoost = n.GetIntValue(); } },
                { "gitStatusBoost", n => { GitStatusBoost = n.GetIntValue(); } },
                { "matchType", n => { MatchType = n.GetStringValue(); } },
                { "pathAlignmentBonus", n => { PathAlignmentBonus = n.GetIntValue(); } },
                { "specialFilenameBonus", n => { SpecialFilenameBonus = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("baseScore", BaseScore);
            writer.WriteIntValue("comboMatchBoost", ComboMatchBoost);
            writer.WriteIntValue("currentFilePenalty", CurrentFilePenalty);
            writer.WriteIntValue("distancePenalty", DistancePenalty);
            writer.WriteBoolValue("exactMatch", ExactMatch);
            writer.WriteIntValue("filenameBonus", FilenameBonus);
            writer.WriteIntValue("frecencyBoost", FrecencyBoost);
            writer.WriteIntValue("gitRecencyBoost", GitRecencyBoost);
            writer.WriteIntValue("gitStatusBoost", GitStatusBoost);
            writer.WriteStringValue("matchType", MatchType);
            writer.WriteIntValue("pathAlignmentBonus", PathAlignmentBonus);
            writer.WriteIntValue("specialFilenameBonus", SpecialFilenameBonus);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
