// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Search request. Supply `query`, or `structured`, or neither (an empty query ranks thewhole index by frecency). Supplying both is rejected rather than silently preferring one.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequest : IParsable
    {
        /// <summary>Query-history combo boost. Only has an effect once a client reports selections via`track-query`.</summary>
        public int? ComboBoostMultiplier { get; set; }
        /// <summary>A path to deprioritise, so the file a caller is already looking at does not dominateits own results. Also feeds the distance bonus for nearby paths.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentFile { get; set; }
#nullable restore
#else
        public string CurrentFile { get; set; }
#endif
        /// <summary>0 lets the engine choose.</summary>
        public int? MaxThreads { get; set; }
        /// <summary>The minComboCount property</summary>
        public int? MinComboCount { get; set; }
        /// <summary>Zero-based page index.</summary>
        public int? Page { get; set; }
        /// <summary>Defaults to `defaults.page_size`.</summary>
        public int? PageSize { get; set; }
        /// <summary>The raw fff query DSL, e.g. `git:modified src/**/*.rs !tests/ user controller`.Passed to the engine byte-for-byte. Glob separators must be `/`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>The structured property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.StructuredQuery? Structured { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.StructuredQuery Structured { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.SearchRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.SearchRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.SearchRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comboBoostMultiplier", n => { ComboBoostMultiplier = n.GetIntValue(); } },
                { "currentFile", n => { CurrentFile = n.GetStringValue(); } },
                { "maxThreads", n => { MaxThreads = n.GetIntValue(); } },
                { "minComboCount", n => { MinComboCount = n.GetIntValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "structured", n => { Structured = n.GetObjectValue<global::ApiSdk.Models.StructuredQuery>(global::ApiSdk.Models.StructuredQuery.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("comboBoostMultiplier", ComboBoostMultiplier);
            writer.WriteStringValue("currentFile", CurrentFile);
            writer.WriteIntValue("maxThreads", MaxThreads);
            writer.WriteIntValue("minComboCount", MinComboCount);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteStringValue("query", Query);
            writer.WriteObjectValue<global::ApiSdk.Models.StructuredQuery>("structured", Structured);
        }
    }
}
#pragma warning restore CS0618
