// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// One file hit, with its score and match highlighting.The engine returns items, scores and match offsets as three parallel arrays; they arezipped here. Nothing is lost, and a generated C# client is far better for it.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchHit : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An indexed file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.FileItemDto? Item { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.FileItemDto Item { get; set; }
#endif
        /// <summary>Which parts of `item.relativePath` matched, in UTF-16 code units. The MCP serverdiscards this information entirely.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.Utf16Range>? MatchRangesUtf16 { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.Utf16Range> MatchRangesUtf16 { get; set; }
#endif
        /// <summary>The complete score breakdown: all 13 fields the engine computes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.ScoreDto? Score { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.ScoreDto Score { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.SearchHit"/> and sets the default values.
        /// </summary>
        public SearchHit()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.SearchHit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.SearchHit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.SearchHit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "item", n => { Item = n.GetObjectValue<global::ApiSdk.Models.FileItemDto>(global::ApiSdk.Models.FileItemDto.CreateFromDiscriminatorValue); } },
                { "matchRangesUtf16", n => { MatchRangesUtf16 = n.GetCollectionOfObjectValues<global::ApiSdk.Models.Utf16Range>(global::ApiSdk.Models.Utf16Range.CreateFromDiscriminatorValue)?.AsList(); } },
                { "score", n => { Score = n.GetObjectValue<global::ApiSdk.Models.ScoreDto>(global::ApiSdk.Models.ScoreDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ApiSdk.Models.FileItemDto>("item", Item);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.Utf16Range>("matchRangesUtf16", MatchRangesUtf16);
            writer.WriteObjectValue<global::ApiSdk.Models.ScoreDto>("score", Score);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
