// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// Constraints as data, for clients that would rather not build DSL strings.Separators are folded in `globs`, `pathSegments`, `filePaths` and `excludePathSegments`,where a separator is unambiguously a separator. The engine&apos;s glob backend treats **only**`/` as a separator, so without folding `src\**\*.rs` would not be applied as a glob atall — it would fall through to fuzzy text matching and quietly return unrelated results.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StructuredQuery : IParsable
    {
        /// <summary>Path segments to exclude.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludePathSegments { get; set; }
#nullable restore
#else
        public List<string> ExcludePathSegments { get; set; }
#endif
        /// <summary>Literal text to exclude.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeText { get; set; }
#nullable restore
#else
        public List<string> ExcludeText { get; set; }
#endif
        /// <summary>Bare extensions, without a dot: `rs`, `md`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Extensions { get; set; }
#nullable restore
#else
        public List<string> Extensions { get; set; }
#endif
        /// <summary>Exact repo-relative file paths.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FilePaths { get; set; }
#nullable restore
#else
        public List<string> FilePaths { get; set; }
#endif
        /// <summary>Engine file-type names, e.g. `rust`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FileTypes { get; set; }
#nullable restore
#else
        public List<string> FileTypes { get; set; }
#endif
        /// <summary>Free-text fuzzy terms. Split on whitespace into parts, as the DSL parser would.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fuzzy { get; set; }
#nullable restore
#else
        public string Fuzzy { get; set; }
#endif
        /// <summary>The gitStatus property</summary>
        public global::ApiSdk.Models.GitStatusConstraint? GitStatus { get; set; }
        /// <summary>Glob patterns, e.g. `src/**/*.rs`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Globs { get; set; }
#nullable restore
#else
        public List<string> Globs { get; set; }
#endif
        /// <summary>Path segments a result must contain, e.g. `src`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PathSegments { get; set; }
#nullable restore
#else
        public List<string> PathSegments { get; set; }
#endif
        /// <summary>Literal text a path must contain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Text { get; set; }
#nullable restore
#else
        public List<string> Text { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.StructuredQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.StructuredQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.StructuredQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "excludePathSegments", n => { ExcludePathSegments = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "excludeText", n => { ExcludeText = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "extensions", n => { Extensions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "filePaths", n => { FilePaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "fileTypes", n => { FileTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "fuzzy", n => { Fuzzy = n.GetStringValue(); } },
                { "gitStatus", n => { GitStatus = n.GetEnumValue<global::ApiSdk.Models.GitStatusConstraint>(); } },
                { "globs", n => { Globs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pathSegments", n => { PathSegments = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "text", n => { Text = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("excludePathSegments", ExcludePathSegments);
            writer.WriteCollectionOfPrimitiveValues<string>("excludeText", ExcludeText);
            writer.WriteCollectionOfPrimitiveValues<string>("extensions", Extensions);
            writer.WriteCollectionOfPrimitiveValues<string>("filePaths", FilePaths);
            writer.WriteCollectionOfPrimitiveValues<string>("fileTypes", FileTypes);
            writer.WriteStringValue("fuzzy", Fuzzy);
            writer.WriteEnumValue<global::ApiSdk.Models.GitStatusConstraint>("gitStatus", GitStatus);
            writer.WriteCollectionOfPrimitiveValues<string>("globs", Globs);
            writer.WriteCollectionOfPrimitiveValues<string>("pathSegments", PathSegments);
            writer.WriteCollectionOfPrimitiveValues<string>("text", Text);
        }
    }
}
#pragma warning restore CS0618
