// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Which readiness stage to block for.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WaitFor
    {
        [EnumMember(Value = "scan")]
        #pragma warning disable CS1591
        Scan,
        #pragma warning restore CS1591
        [EnumMember(Value = "indexing")]
        #pragma warning disable CS1591
        Indexing,
        #pragma warning restore CS1591
        [EnumMember(Value = "watcher")]
        #pragma warning disable CS1591
        Watcher,
        #pragma warning restore CS1591
    }
}
