// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// A workspace as clients see it.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspaceResource : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Git worktree root, if one was discovered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitRoot { get; set; }
#nullable restore
#else
        public string GitRoot { get; set; }
#endif
        /// <summary>The hasGitRepo property</summary>
        public bool? HasGitRepo { get; set; }
        /// <summary>Stable identifier, derived from the directory&apos;s filesystem identity. Re-creating thesame root — under any spelling, and across server restarts — returns this same id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Effective idle-eviction timeout, derived from `timeToReadyMs`.</summary>
        public long? IdleTimeoutSecs { get; set; }
        /// <summary>Files currently in the index.</summary>
        public int? IndexedFiles { get; set; }
        /// <summary>True when the root resolved to a UNC path, mapped drives included. Reported forvisibility only: freshness and eviction key off measured cost, not path type.</summary>
        public bool? IsNetworkPath { get; set; }
        /// <summary>The isScanning property</summary>
        public bool? IsScanning { get; set; }
        /// <summary>The content index is built. Fuzzy grep needs this, and the watcher is installed onlyafter it completes.</summary>
        public bool? IsWarmupComplete { get; set; }
        /// <summary>The isWatcherReady property</summary>
        public bool? IsWatcherReady { get; set; }
        /// <summary>The lastScanAt property</summary>
        public DateTimeOffset? LastScanAt { get; set; }
        /// <summary>The settings this workspace was actually built with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.EffectiveOptions? Options { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.EffectiveOptions Options { get; set; }
#endif
        /// <summary>Effective automatic rescan interval, derived from `timeToReadyMs`.</summary>
        public long? RescanIntervalSecs { get; set; }
        /// <summary>The resolved root, with any verbatim `\\?\` prefix stripped. Display-and-open safe;not an identity key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Root { get; set; }
#nullable restore
#else
        public string Root { get; set; }
#endif
        /// <summary>Files seen by the most recent scan.</summary>
        public int? ScannedFilesCount { get; set; }
        /// <summary>Readiness, as a single field a client can branch on.</summary>
        public global::ApiSdk.Models.WorkspaceStatus? Status { get; set; }
        /// <summary>Time from construction to the readiness stage the creating call waited for. Drivesboth derived intervals below.</summary>
        public long? TimeToReadyMs { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.WorkspaceResource"/> and sets the default values.
        /// </summary>
        public WorkspaceResource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.WorkspaceResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.WorkspaceResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.WorkspaceResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "gitRoot", n => { GitRoot = n.GetStringValue(); } },
                { "hasGitRepo", n => { HasGitRepo = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "idleTimeoutSecs", n => { IdleTimeoutSecs = n.GetLongValue(); } },
                { "indexedFiles", n => { IndexedFiles = n.GetIntValue(); } },
                { "isNetworkPath", n => { IsNetworkPath = n.GetBoolValue(); } },
                { "isScanning", n => { IsScanning = n.GetBoolValue(); } },
                { "isWarmupComplete", n => { IsWarmupComplete = n.GetBoolValue(); } },
                { "isWatcherReady", n => { IsWatcherReady = n.GetBoolValue(); } },
                { "lastScanAt", n => { LastScanAt = n.GetDateTimeOffsetValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::ApiSdk.Models.EffectiveOptions>(global::ApiSdk.Models.EffectiveOptions.CreateFromDiscriminatorValue); } },
                { "rescanIntervalSecs", n => { RescanIntervalSecs = n.GetLongValue(); } },
                { "root", n => { Root = n.GetStringValue(); } },
                { "scannedFilesCount", n => { ScannedFilesCount = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::ApiSdk.Models.WorkspaceStatus>(); } },
                { "timeToReadyMs", n => { TimeToReadyMs = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("gitRoot", GitRoot);
            writer.WriteBoolValue("hasGitRepo", HasGitRepo);
            writer.WriteStringValue("id", Id);
            writer.WriteLongValue("idleTimeoutSecs", IdleTimeoutSecs);
            writer.WriteIntValue("indexedFiles", IndexedFiles);
            writer.WriteBoolValue("isNetworkPath", IsNetworkPath);
            writer.WriteBoolValue("isScanning", IsScanning);
            writer.WriteBoolValue("isWarmupComplete", IsWarmupComplete);
            writer.WriteBoolValue("isWatcherReady", IsWatcherReady);
            writer.WriteDateTimeOffsetValue("lastScanAt", LastScanAt);
            writer.WriteObjectValue<global::ApiSdk.Models.EffectiveOptions>("options", Options);
            writer.WriteLongValue("rescanIntervalSecs", RescanIntervalSecs);
            writer.WriteStringValue("root", Root);
            writer.WriteIntValue("scannedFilesCount", ScannedFilesCount);
            writer.WriteEnumValue<global::ApiSdk.Models.WorkspaceStatus>("status", Status);
            writer.WriteLongValue("timeToReadyMs", TimeToReadyMs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
