// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Readiness, as a single field a client can branch on.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkspaceStatus
    {
        [EnumMember(Value = "initialising")]
        #pragma warning disable CS1591
        Initialising,
        #pragma warning restore CS1591
        [EnumMember(Value = "indexing")]
        #pragma warning disable CS1591
        Indexing,
        #pragma warning restore CS1591
        [EnumMember(Value = "ready")]
        #pragma warning disable CS1591
        Ready,
        #pragma warning restore CS1591
    }
}
