// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using ApiSdk.V1.Workspaces.Item.Git;
using ApiSdk.V1.Workspaces.Item.Glob;
using ApiSdk.V1.Workspaces.Item.Grep;
using ApiSdk.V1.Workspaces.Item.History;
using ApiSdk.V1.Workspaces.Item.MultiGrep;
using ApiSdk.V1.Workspaces.Item.Rescan;
using ApiSdk.V1.Workspaces.Item.Search;
using ApiSdk.V1.Workspaces.Item.TrackAccess;
using ApiSdk.V1.Workspaces.Item.TrackQuery;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.V1.Workspaces.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspacesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The git property</summary>
        public global::ApiSdk.V1.Workspaces.Item.Git.GitRequestBuilder Git
        {
            get => new global::ApiSdk.V1.Workspaces.Item.Git.GitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The glob property</summary>
        public global::ApiSdk.V1.Workspaces.Item.Glob.GlobRequestBuilder Glob
        {
            get => new global::ApiSdk.V1.Workspaces.Item.Glob.GlobRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The grep property</summary>
        public global::ApiSdk.V1.Workspaces.Item.Grep.GrepRequestBuilder Grep
        {
            get => new global::ApiSdk.V1.Workspaces.Item.Grep.GrepRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The history property</summary>
        public global::ApiSdk.V1.Workspaces.Item.History.HistoryRequestBuilder History
        {
            get => new global::ApiSdk.V1.Workspaces.Item.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiGrep property</summary>
        public global::ApiSdk.V1.Workspaces.Item.MultiGrep.MultiGrepRequestBuilder MultiGrep
        {
            get => new global::ApiSdk.V1.Workspaces.Item.MultiGrep.MultiGrepRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rescan property</summary>
        public global::ApiSdk.V1.Workspaces.Item.Rescan.RescanRequestBuilder Rescan
        {
            get => new global::ApiSdk.V1.Workspaces.Item.Rescan.RescanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::ApiSdk.V1.Workspaces.Item.Search.SearchRequestBuilder Search
        {
            get => new global::ApiSdk.V1.Workspaces.Item.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trackAccess property</summary>
        public global::ApiSdk.V1.Workspaces.Item.TrackAccess.TrackAccessRequestBuilder TrackAccess
        {
            get => new global::ApiSdk.V1.Workspaces.Item.TrackAccess.TrackAccessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trackQuery property</summary>
        public global::ApiSdk.V1.Workspaces.Item.TrackQuery.TrackQueryRequestBuilder TrackQuery
        {
            get => new global::ApiSdk.V1.Workspaces.Item.TrackQuery.TrackQueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Workspaces.Item.WorkspacesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspacesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Workspaces.Item.WorkspacesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspacesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Evict a workspace now, releasing its index, watcher threads and database handles.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.Problem">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ApiSdk.Models.Problem.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch one workspace, including current readiness. This is the poll target after a `202`.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.WorkspaceResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.Problem">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.WorkspaceResource?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.WorkspaceResource> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ApiSdk.Models.Problem.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.WorkspaceResource>(requestInfo, global::ApiSdk.Models.WorkspaceResource.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Evict a workspace now, releasing its index, watcher threads and database handles.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Fetch one workspace, including current readiness. This is the poll target after a `202`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Workspaces.Item.WorkspacesItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.V1.Workspaces.Item.WorkspacesItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.V1.Workspaces.Item.WorkspacesItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorkspacesItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorkspacesItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
